apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1
  namespace: xnet
  labels:
    app: my-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: mywebapp
        image: mywebapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app1-service
  namespace: xnet
  labels:
    app: my-app1
spec:
  selector:
    app: my-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
